### ISSUE TITLE
Add attribution to the Yossi Yovel lab to the ReadMe

### ISSUE THREAD

**Issue by aza** [earthspecies/library#13]
The ReadMe should:

* Give attribution and acknowledgement to the Yossi Yovel lab for the data set (creating this data set was a time consuming and intense undertaking!)
* Describe the data set (can probably quote description in paper) ... how was it created, the purpose for which it was created, etc.

For this project in particular, where everything is collaboration/interdependence, attribution to/centering biologists and field researchers is important.

Tagging @oliver-adams-b (I can’t assign this ticket to you, so assigned it to @radekosmulski)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1198183573587004/1198566179432804) by [Unito](https://www.unito.io/learn-more)

**Comment by kzacarian** [comment]
Here's the citation for the data collection, if it's helpful. Which I got from [here](https://figshare.com/collections/An_annotated_dataset_of_Egyptian_fruit_bat_vocalizations_across_varying_contexts_and_during_vocal_ontogeny/3666502).  

Prat, Yosef; Taub, Mor; Pratt, Ester; Yovel, Yossi (2017): An annotated dataset of Egyptian fruit bat vocalizations across varying contexts and during vocal ontogeny. figshare. Collection. https://doi.org/10.6084/m9.figshare.c.3666502.v2

**Comment by radekosmulski** [comment]
Citation added
