### ISSUE TITLE
Anuran Datasets!

### ISSUE THREAD

**Issue by oliver-adams-b** [earthspecies/library#18]
[This](https://figshare.com/s/4af71d71d94e04afcd5f) dataset contains Mel-spectrogram representations of audio recordings labeled by species type across 10 species. _Anura_ is an order of amphibians found mostly in South America, and an _Anuran_ is just a frog/toad of that order. So this dataset is just a bunch of recordings of cute/colorful frogs!  The data are stored in `.npy` format, 441 kHz and have durations varying from 3 to 360 seconds. There are nearly 2.4k samples across the testing, validation, and training sets.  Some analysis and explorations into the Anuran dataset can be found in the paper [here](https://asa.scitation.org/doi/abs/10.1121/1.5118245).

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1198183573587004/1198566176972625) by [Unito](https://www.unito.io/learn-more)

**Comment by radekosmulski** [comment]
Closing - the dataset is interesting but we don't want to include in our library a dataset that starts with spectrograms, we would like to start with audio.
