### ISSUE TITLE
Watkins Whale(+) Datasets

### ISSUE THREAD

**Issue by oliver-adams-b** [earthspecies/library#19]
Before I got the sweet lead on the Egyptian fruit bat datasets, I was planning on getting my noises from the [Watkins Marine Mammal Sound Database](https://cis.whoi.edu/science/B/whalesounds/index.cfm). Recordings from many different marine mammal vocalizations can be downloaded directly from the site, along with the metadata unique to each recording. I created [this](https://github.com/oliver-adams-b/library/blob/main/egyptian_fruit_bat/data_wranglers/watkins_best_of_datascrape.py) webscraper a few weeks ago so that I could download and organize the audio/metadata for the 'Best Of' selection of recordings from the website. You can find the archive of the datasets I downloaded from the site [here](https://archive.org/details/watkins_best_of_whales_202008). I originally just downloaded recordings from whales, but there are a lot more species to be studied!

The recordings are sampled at varying rates and quality, with some dating back to around 1960! There is a varying number of samples for each of the 12 species of whales whose vocalizations I grabbed. All vocalizations, however, are stored in `.wav` format, with the metadata stored in `.csv`. The vocalizations can be labeled by species through their parent folder, but to predict other fields you'll need to go through the metadata. The information required to decode the metadata can be found [here](https://cis.whoi.edu/science/B/whalesounds/WHOI-92-31.pdf). On the website it is stated that the data is free to download and use for personal or academic (non commercial) use.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1198183573587004/1198566178289483) by [Unito](https://www.unito.io/learn-more)

**Comment by radekosmulski** [comment]
This one is done!

**Comment by leuc** [comment]
Hi, @oliver-adams-b 

i have been working on scraping and cleaning Watkins database. I am almost done with processing all database fields and will be pushing more updates over the holidays. 

A search and World Map view is also available on the [website](https://marine-mammal.soundwave.cl/).

A work-in-progress description of the database content: https://marine-mammal.soundwave.cl/data.html

Source Code at: https://codeberg.org/dleucas/wmmsdb

I would like to make the data available in various formats for better integration with other datasets. Linked data and such.
A GeoJSON conversion is already available and used by the World Map view.

I'd welcome any suggestions for good formats and namespaces to use.
