### ISSUE TITLE
Earth Species Library datasets <-> Archive.org

### ISSUE THREAD

**Issue by bs** [earthspecies/library#24]
Right now they live in:

- [Earth Species Project Collection](https://archive.org/details/earth-species-project)
  - Macaques, Otters, and a reference to author of macaques
- [with creator metadata 'Earth Species'](https://archive.org/search.php?query=creator%3A%22Earth+Species%22)
  - II.IO workshop talk
  - This seems to also fuzzy match on 'Earth Species Project'
- [Yossi Yovel's Egyptian fruit bat dataset, uploaded by @oliver-adams-b]

A dataset includes:
- binary compressed file of all data, to be downloaded for training in a jupyter notebook
- Extracted contents to be browsed and played online
- Associated files: papers, videos, photos

@markjohngraham, how does map to Archive.org taxonomy?

**Comment by radekosmulski** [comment]
@bs are we okay to close this issue?
