### ISSUE TITLE
💾 Upload Brenda McCowan's Dog Bark data to ESP Library

### ISSUE THREAD

**Issue by kzacarian** [earthspecies/library#29]
@kzacarian commented on [Thu Oct 29 2020](https://github.com/earthspecies/library.internal/issues/19)

We're grateful to receive the first of several datasets from [Brenda McCowan](https://bmccowanlab.com/), PhD, Professor, Population Health & Reproduction, Animal Behavior Laboratory for Welfare & Conservation, School of Veterinary Medicine and Unit Leader & Core Scientist, Neuroscience & Behavior Unit, [California National Primate Research Center at UC Davis](https://cnprc.ucdavis.edu/brenda-mccowan/). 

Data is available at [Box](https://app.box.com/folder/125225492884?s=nucq7nxd2gvjwiblac7s7ezadbllv39r&utm_campaign=collab%20auto%20accept%20user&utm_medium=email&utm_source=trans) link and includes the raw audio, annotations, and paper which was published with this data. 

**Abstract**
_In this study we sought to determine whether dog barks could be divided into subtypes based on context. We recorded barking from 10 adult dogs, Canis familiaris, of six breeds in three different test situations: (1) a disturbance situation in which a stranger rang the doorbell, (2) an isolation situation in which the dog was locked outside or in a room isolated from its owner and (3) a play situation in which either two dogs or a human and a dog played together. We analysed spectrograms of 4672 barks using macros that took 60 sequential frequency measurements and 60 sequential amplitude measurements along the length of the call. Statistical analyses revealed that barks are graded vocalizations that range from harsh, low-frequency, unmodulated calls to harmonically rich, higher-frequency, modulated calls. The harsh, low-frequency, unmodulated barks were more commonly given in the disturbance situation, and the more tonal, higher-pitch, modulated barks were more commonly given in the isolation and play situations. Disturbance barks were also longer in duration with more rapid repetition than the barks given in other contexts. Discriminant analysis revealed that dog barks can be divided into different subtypes based on context even within individual dogs, and that dogs can be identified by their bark spectrograms despite the context of the bark._

[Barking in domestic dogs: Context specificity and individual identification. Yin S., McCowan B. (2004)  Animal Behaviour,  68  (2) , pp. 343-355.](https://doi.org/10.1016/j.anbehav.2003.07.016)

**Comment by radekosmulski** [comment]
@kzacarian I am unable to access the data on box, I tried to create an account but this doesn't seem like the right approach

Could I please ask you for your help? Not sure how to proceed

**Comment by radekosmulski** [comment]
this is done! 🙂
