### ISSUE TITLE
💾  Upload Orcasound data to ESP Library 

### ISSUE THREAD

**Issue by kzacarian** [earthspecies/library#32]
[Orcasound](https://www.orcasound.net/) is a cooperative effort of many dedicated individuals and organizations. Their “[AI for Orcas](https://www.orcasound.net/portfolio/ai-for-orcas-open-bioacoustic-data-science/)” project represents a 2-decade effort by the Orcasound and open-source communities to develop machine learning models to classify signals made by killer whales (calls, clicks, and whistles), in real-time, starting with the calls of the endangered orcas known as the Southern Resident Killer Whales (SRKWs). An important part of the process is generating high-quality and open-access training and testing data sets. On the [Orcasound Github](https://github.com/orcasound/orcadata/blob/master/access.md), they share all of their data publicly, via AWS. 

The repository also has links to [Orca Machine Learning resources](https://github.com/orcasound/orcadata/wiki/Orca-ML-resources).

**Comment by radekosmulski** [comment]
done! 🙂
