### ISSUE TITLE
💾 Inspect & (maybe) Upload NIPS4Bplus: a richly annotated birdsong audio dataset

### ISSUE THREAD

**Issue by kzacarian** [earthspecies/library#33]
NIPS4Bplus, is the first richly annotated birdsong audio dataset, that is comprised of recordings containing bird vocalizations along with their active species tags plus the temporal annotations acquired for them. NIPS4Bplus contains temporal annotations for the recordings that comprised the training set of the 2013 Neural Information Processing Scaled for Bioacoustics (NIPS4B) challenge for bird song classification (http://sabiod.univ-tln.fr/nips4b/challenge1.html).  

Approximately **30 h** of field recordings were collected. Any recording longer than 5 s was split into multiple 5 s files. SonoChiro, a chirp detection tool used for bat vocalization detection, was used on each file to identify recordings with bird vocalizations (http://www.leclub-biotope.com/fr/72-sonochiro). 

Stratified random sampling was then applied to all acquired recordings, based on locations and clustering of features, to maximize the diversity in the labeled dataset, resulting in nearly **5,000** files being chosen. Following the first stage of selection, manual annotations were produced for the classes active in these 5,000 files and any recordings that contained unidentified species’ vocalizations were discarded. 

Furthermore, the training set and testing set recordings were allocated so that the same species were active in both. Finally, for training purposes, only species that could be covered by at least seven recordings in the training set were included in the final dataset, the rest were considered rare species’ occurrences that would make it hard to train any classifier; hence, they were discarded. The final training and testing set consists of **687 files** of the total duration of less than an hour, and **1,000 files** of the total duration of nearly two hours, respectively.

The data is accessible at Figshare (https://doi.org/10.6084/m9.figshare.6798548) 

Citation: Morfi V, Bas Y, Pamuła H, Glotin H, Stowell D. 2019. NIPS4Bplus: a richly annotated birdsong audio dataset. PeerJ Computer Science 5:e223 https://doi.org/10.7717/peerj-cs.223

**Comment by radekosmulski** [comment]
I have added this as [bird_songs](https://github.com/earthspecies/library/tree/main/bird_songs).
