### ISSUE TITLE
document steps for adding a new dataset to the library

### ISSUE THREAD

**Issue by radekosmulski** [earthspecies/library#9]
I would like to let you know that I have kicked off the work on adding a document on a adding dataset to the library!

It is a rough draft for now. You can find it [here](https://github.com/earthspecies/library/blob/main/howto_add_a_new_dataset_to_the_library.md)

@bs @aza @kzacarian @pcbermant @oliver-adams-b would really love your thoughts. I think we can work on the markdown directly? 

Is there anything high level that I am missing? Also - please feel free to put more substance around these steps.

All thoughts / edits / contributions to the doc are much welcome! :slightly_smiling_face:

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1198183573587004/1198566177875615) by [Unito](https://www.unito.io/learn-more)

**Comment by aza** [comment]
@radekosmulski I love the idea of you adding the Tawny owl data set and documenting the process. I think that praxis will ground the document and make it super helpful as an on-ramp.

**Comment by kzacarian** [comment]
Great pass @radekosmulski , I love it!  I took a pass at correcting some grammar and spelling errors, and adding further description to illustrate certain steps. You can see my revisions [here](https://docs.google.com/document/d/1EYw7Yg3LiZA61fsJR9kMC3INNFZ5h1w_OFA0Gt2k65A/edit?usp=sharing). re: @aza and @bs @oliver-adams-b

**Comment by oliver-adams-b** [comment]
I think this would be super helpful for future contributors to the library, thanks @radekosmulski for doing the legwork to get this started! I was thinking it might be helpful to add a 'next steps' section to READMEs, where it may apply, just a section through which new contributors can peruse to give them some inspiration or potential next steps! (i.e. citing research papers whose results could be reapplied in a new context or improved with new methods)

**Comment by aza** [comment]
This is great start, @radekosmulski <https://github.com/radekosmulski>. I
started cleaning up the opening paragraphs. So happy to see this.

There is a lot to flush out here to make it sendable to a competent machine
learning student and have them be able to understand what a suitable data
set is, grab one, explore & tutorialize it, and then add it to the archive
and the ESP Library.

@oliver-adams-b, given your experience would love your edits/additions so
that this document would have been/is useful for you!

-- aza | ɐzɐ --

**Comment by kzacarian** [comment]
Thank you @oliver-adams-b for adding your thoughts and input into the document [(link to draft on Google Docs](https://docs.google.com/document/d/1EYw7Yg3LiZA61fsJR9kMC3INNFZ5h1w_OFA0Gt2k65A/edit?usp=sharing)). IMHO, this baby is ready to ship. 

cc: @radekosmulski , @aza, @bs

**Comment by radekosmulski** [comment]
This is so well written now - I absolutely love this! 😍 Outstanding job @kzacarian and @oliver-adams-b!!!

I updated the [file](https://github.com/earthspecies/library/blob/main/howto_add_a_new_dataset_to_the_library.md) on github. Will fill in the missing pieces when I work on the tawny owl dataset.

**Comment by bs** [comment]
Next steps are for me to finalize this document with IA details and edits.

**Comment by radekosmulski** [comment]
We are tracking this on Asana -- more work to come. Closing this as some of the conversation here is not relevant to this work anymore.
